### ISSUE TITLE
All links under Agentverse components, including "Open Network," "Courses," "Getting Started," and "Browse by Product," Not Opening in New Tab

### ISSUE THREAD

**Issue by harshpatel199259** [fetchai/deprecated-docs#1006]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Other

### Expected Behavior / Content

All links under Agentverse components, including "Open Network," "Courses," "Getting Started," and "Browse by Product," should open in a new tab by default. Additionally, users should have the ability to right-click on links to open them in a new tab.

### Observed Behavior / Content

Currently, the links do not open in a new tab by default, and there is no right-click option available to open the links in a new tab.

**Comment by devjsc** [comment]
The links are to content within the same site so it's not expected by the user to be taken to a new window/tab
