### ISSUE TITLE
Submit feedback not responding

### ISSUE THREAD

**Issue by harshpatel199259** [fetchai/deprecated-docs#1007]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Technical Bug (unexpected behavior)

### Observed Behavior / Content

Submit feedback not responding
https://fetch.ai/docs/apis#asi-alliance-wallet-apis

![image10](https://github.com/user-attachments/assets/c49fd882-f459-4bcd-ad37-4cad5c926814)

**Comment by devjsc** [comment]
Investigating, there is an issue in deployment somewhere.

**Comment by devjsc** [comment]
fixed
