### ISSUE TITLE
No Confirmation Message After Successful Signup

### ISSUE THREAD

**Issue by harshpatel199259** [fetchai/deprecated-docs#1008]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Technical Bug (unexpected behavior)

### Expected Behavior / Content

After signing up with a valid email address, the user should see a confirmation message indicating successful signup, such as "Signup successful" or "Thanks for signing up!"

### Observed Behavior / Content

When a user signs up with a correct email address, there is no confirmation message displayed, leaving the user uncertain about the success of their signup.

**Comment by devjsc** [comment]
Hello @harshpatel199259 , where is there a sign up link? 😬

**Comment by devjsc** [comment]
Interesting, will look into this now. I think this may be the hint as to why the feedback form isn't working either
