### ISSUE TITLE
Clicking on the analytics option is redirecting to the guides page.

### ISSUE THREAD

**Issue by harshpatel199259** [fetchai/deprecated-docs#1010]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Incorrect or missing Content

### Observed Behavior / Content

Clicking on the analytics option is redirecting to the guides page.
![image6](https://github.com/user-attachments/assets/a3ca16fd-5b67-4ed7-9d50-ddd6fc8bd682)

**Comment by devjsc** [comment]
@FelixNicolaeBucsa Can we disable this link?

**Comment by FelixNicolaeBucsa** [comment]
Have just removed it @devjsc

**Comment by FelixNicolaeBucsa** [comment]
PR here: https://github.com/fetchai/docs/pull/1012
