### ISSUE TITLE
FET tx updates 

### ISSUE THREAD

**Issue by devjsc** [fetchai/deprecated-docs#1027]
### Observed Behavior / Content

 I have a few questions regarding the memo attached to the Fetch transaction:
- What is the character limit or size limit?
- Are there any limitations? For example, can I attach a blob object within the required limit?
- If the transaction is added to the chain, will the memo be stored as well? What happens in case of a migration—will the transaction data still be available afterward?

**Comment by FelixNicolaeBucsa** [comment]
What document is this referring to?

**Comment by devjsc** [comment]
I think we need to add this as necessary information when creating a TX when using cosmpy, reach out to @pbukva or @MissingNO57 on Slack to see if they can share this information with you
