### ISSUE TITLE
Issue: <Issue Related to /guides/fetch-network/reconciliation-service>

### ISSUE THREAD

**Issue by msking22** [fetchai/deprecated-docs#1063]
Good morning,

Trying to utilize the reconciliation service and I receive a 500: Internal Server Error. Is this service still active?

**Comment by NikoDMT** [comment]
Good morning. We've recently pushed a major upgrade on reconciliation with final polish in preparation. Guides and tutorials will soon be made available across our documentation that will facilitate access to migrated funds. We will issue an update across X (formerly twitter), telegram and discord once everything is prepared.

**Comment by msking22** [comment]
Thank you very much!
