### ISSUE TITLE
Broken link on "CI with AVCTL and Github Actions" Guide 

### ISSUE THREAD

**Issue by deepakfetchai** [fetchai/deprecated-docs#1068]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Incorrect or missing Content

### Observed Behavior / Content

![image](https://github.com/user-attachments/assets/6d709cb6-8dd0-4142-aec9-5c4247190774)

**Broken links:**
- https://fetch.ai/docs/guides/agentverse/avctl/guides/agentverse/avctl/avctl
- https://fetch.ai/docs/guides/agentverse/avctl/guides/agentverse/avctl/avctl-hosting

**Comment by gautamgambhir97** [comment]
This has been fixed
