### ISSUE TITLE
Feedback: How to request the service from a blockchain transaction when the agent is on-chain?	/guides/agents/cleaning-demo

### ISSUE THREAD

**Issue by devjsc** [fetchai/deprecated-docs#291]
23	positive	How to request the service from a blockchain transaction when the agent is on-chain?	/guides/agents/cleaning-demo

**Comment by devjsc** [comment]
This guide has been deleted.

We need to add a redirect for this to examples: https://fetch.ai/docs/examples/intermediate/agents-cleaning-demo#cleaning-service-with-agents.

A guide for sending TXs with agents is here: https://fetch.ai/docs/guides/agents/intermediate/send-tokens

**Comment by FelixNicolaeBucsa** [comment]
Where do we want to redirect people from?
