### ISSUE TITLE
feedback: DELTA-V Chat API doc language is super technical & hard to understand 

### ISSUE THREAD

**Issue by cmaliwal** [fetchai/deprecated-docs#414]
> Most of the endpoints depends on various instances and are considered parameters for the actual endpoint, but these are not meant to be passed directly by the user.
Instead, these instance-dependent elements are integrated and managed directly by the backend system. We refer to them as *name_parameter, where the asterisk (*) is used to denote a specific instance-dependent parameter that the route relies on.

https://fetch.ai/docs/apis/ai-engine/chat

**Comment by devjsc** [comment]
API docs has been updated, and we will continue to revisit this regularly
