### ISSUE TITLE
Add category for links to external resources

### ISSUE THREAD

**Issue by FelixNicolaeBucsa** [fetchai/deprecated-docs#683]
**An 'extras category that summaries all the previously mentioned links to external resources. This category also includes 'FAQs'** 
Much of the content for 'FAQs' can be obtained by sending surveys to team members who attended the Summit. The 'comments' section detailed in the next suggestion could also be utilised.
![image](https://github.com/fetchai/docs-v2/assets/83825570/065d16d9-79b2-44e3-8e3d-a7654a7423b7)

![image](https://github.com/fetchai/docs-v2/assets/83825570/174c5e4f-b224-4492-9e6e-50b1103905f1)

**Comment by devjsc** [comment]
We are updating this, please see this issue: https://github.com/fetchai/docs/issues/682
