### ISSUE TITLE
Sometimes bookmarks arent saved (page is bookmarked but bookmark list is empty)

### ISSUE THREAD

**Issue by FelixNicolaeBucsa** [fetchai/deprecated-docs#688]
Sometimes bookmarks arent saved (page is bookmarked but bookmark list is empty)
<img width="309" alt="Screenshot 2024-06-21 at 14 43 02" src="https://github.com/fetchai/docs-v2/assets/71661683/6acdf8af-6865-430f-84ca-99ae8ce9fd2b">

**Comment by gautamgambhir97** [comment]
@FelixNicolaeBucsa We have removed the functionality of bookmarks from docs , so I am closing this issue
