### ISSUE TITLE
Issue with Tags and tags filtering

### ISSUE THREAD

**Issue by FelixNicolaeBucsa** [fetchai/deprecated-docs#689]
The tags and tag filtering aren't very intuitive:

- can only filter by a tag from a page that already has a tag in it
- when selecting a tag for filtering it isnt clear what tag is selected
- its not quite clear that the tags are even selectable + what happens when you click one

**Comment by devjsc** [comment]
Tags have been redesigned, and their flow is simpler - I think that resolves this issue.
