### ISSUE TITLE
Issues for User-specific Inputs in different guides

### ISSUE THREAD

**Issue by FelixNicolaeBucsa** [fetchai/deprecated-docs#699]
### User-specific Input - [Agent Functions](https://fetch.ai/docs/guides/agents/intermediate/agent-functions)

In several guides, part of the example code must be replaced with user-specific input (for example, an agent address or an IP address). 
In some cases, the code is split up into small code blocks that are all explained individually, however in other cases these appear in large code blocks that are expected to be copy/pasted by the user. The description accompanying these code blocks rarely mentions the replacements that need to be made.
I would suggest mentioning the replacement in the description. Additionally, for cases like an IP address, a description on how to find your IP address for users who do not know could be useful (eg ipconfig).

**Comment by devjsc** [comment]
Hey @FelixNicolaeBucsa could you check that all code examples that require port, seed or name changes in code are explicitly stated in the proceeding block of text?

**Comment by FelixNicolaeBucsa** [comment]
Sure thing @devjsc
