### ISSUE TITLE
Add Version Control info

### ISSUE THREAD

**Issue by FelixNicolaeBucsa** [fetchai/deprecated-docs#701]
Implementation: Each version of the documentation should correspond to a specific version of uAgents, with clear navigation to switch between versions.
Benefits: Ensures users can access the relevant documentation for the specific version of uAgents they are using, preventing confusion and errors.

**Comment by devjsc** [comment]
This has been moved to an internal bug tracking to be prioritised in an upcoming sprint.

**Comment by devjsc** [comment]
Version controlling will be implemented once we're at a 1.0 release of uAgents.
