### ISSUE TITLE
Changes to Links into Clickable Cards

### ISSUE THREAD

**Issue by FelixNicolaeBucsa** [fetchai/deprecated-docs#724]
**Changes to Links into Clickable Cards**

<img width="936" alt="Screenshot 2024-07-02 at 11 47 58 PM" src="https://github.com/fetchai/docs-v2/assets/106014185/6f34162d-b4f5-4d13-bc05-014d4c1de23b">

**Comment by devjsc** [comment]
Nice idea, one for @gokhunguneyhan

**Comment by devjsc** [comment]
Could this be added as a suggestion in notion @rishankjhavar ?

**Comment by devjsc** [comment]
After in internal review, the design team are happy with the current layout of links. However we will come back to this in the next update of docs.
