### ISSUE TITLE
Issue in agents communication via wallet guide

### ISSUE THREAD

**Issue by FelixNicolaeBucsa** [fetchai/deprecated-docs#734]
### Getting error:

<img width="1300" alt="Screenshot 2024-06-27 at 8 38 32 PM" src="https://github.com/fetchai/docs-v2/assets/111856910/93551f1a-6ae8-44b5-a015-9f8e1f1132de">

### Debugging:

As it showing babble module not found, as the error inside the uagent package library but still I try to install the babble by using “pip install babble”

But still getting error: \

<img width="1301" alt="Screenshot 2024-06-27 at 8 38 48 PM" src="https://github.com/fetchai/docs-v2/assets/111856910/82b5fc9b-96e7-4aa2-a1f3-19805151b568">

### Solution:

Not found! Still searching…

**Comment by abhifetch** [comment]
@jrriehl Can you help us with this for guide. (https://fetch.ai/docs/examples/intermediate/wallet-messaging)
We are still getting the babble module not found error when we are sending messages to wallet of other agents.
