### ISSUE TITLE
App store link is not correct on wallet guide. 

### ISSUE THREAD

**Issue by cmaliwal** [fetchai/deprecated-docs#814]
App store link is not correct on wallet guide. 
https://fetch.ai/docs/guides/fetch-network/fetch-wallet/mobile-wallet/get-started

current: 	https://apps.apple.com/au/app/
correct: https://apps.apple.com/in/app/fetch-ai-wallet/id1641087356

**Comment by gautamgambhir97** [comment]
This has been fixed
