### ISSUE TITLE
Update AI Engine guides to reference AI Engine installations 

### ISSUE THREAD

**Issue by devjsc** [fetchai/deprecated-docs#819]
On pages where we explicitl use uagents_ai_engine library let's reference that installation. 

pages like: https://fetch.ai/docs/guides/agents/intermediate/ai-engine-compatible-agent should mention the install requirements.

**Comment by devjsc** [comment]
Let's also update personality info in 

https://fetch.ai/docs/guides/agents/intermediate/ai-engine-compatible-agent

https://fetch.ai/docs/guides/agents/intermediate/primary-secondary-functions

https://fetch.ai/docs/guides/agents/advanced/utilizing-api-to-build-network-of-task-and-subtask

let's discuss how we make the persnality reqs for delaV more consistent across pages; perhaps a page discussing AI Engine personalities we can link back to?

**Comment by FelixNicolaeBucsa** [comment]
@devjsc Added information for comment above in: https://github.com/fetchai/docs/pull/825. Waiting for additional information and details from @qati or @zmezei to create that concepts page about AI Engine personalities.
