### ISSUE TITLE
Inconsistent tone with other headings || docs landing page 

### ISSUE THREAD

**Issue by cmaliwal** [fetchai/deprecated-docs#828]
![image](https://github.com/user-attachments/assets/7c1cebad-a652-4660-8510-24ee59506aca)

**Comment by cmaliwal** [comment]
Fetch wallet -> Fetch Wallet

**Comment by FelixNicolaeBucsa** [comment]
https://github.com/fetchai/docs/pull/803

**Comment by devjsc** [comment]
fixed with 803
