### ISSUE TITLE
Improve Agentverse Guide with Clear Login Instructions to Prevent 404 Errors

### ISSUE THREAD

**Issue by cmaliwal** [fetchai/deprecated-docs#831]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) to make sure this feature has not already been requested

### Feature

Hi team,

I’ve reviewed our guide on creating Agents and Agent Functions in Agentverse using APIs:
[Agent Function Creation APIs](https://fetch.ai/docs/guides/apis/agent-function-creation-apis).

There’s a specific line that might affect our SEO and user experience:

"Go to Profile section in Agentverse :arrow_upper_right:."
If users are not logged in, they will be redirected to a 404 page. This could confuse users and hurt our SEO.

To improve this, I suggest adding clear instructions for logging in first. Here’s the revised version:

How to Get Agentverse API Tokens:

Log in to Your Agentverse Account:
Go to the Agentverse login page and log in with your credentials.
Access the Profile Section:
Once logged in, navigate to your Profile section in Agentverse.
Ensure you log in to avoid encountering a 404 error.

Please update the guide accordingly to enhance user experience and SEO.

**Comment by FelixNicolaeBucsa** [comment]
https://github.com/fetchai/docs/pull/836
