### ISSUE TITLE
Missing H1 Tag on Documentation Homepage

### ISSUE THREAD

**Issue by cmaliwal** [fetchai/deprecated-docs#832]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) to make sure this feature has not already been requested

### Feature

The documentation homepage is missing an H1 tag. For optimal SEO performance, each page should contain exactly one H1 tag. The H1 tag serves as the primary heading and helps search engines understand the main topic of the page. Without an H1 tag, the page's SEO ranking can be negatively affected, reducing visibility in search engine results. Adding an H1 tag will improve the structure and accessibility of the content, ensuring better search engine indexing and user experience.

**Comment by devjsc** [comment]
Hey @gautamgambhir97 can we update the front page to use H1? looks like it's a custom css obj for the headers
