### ISSUE TITLE
Update AI Engine Package Version in Agents 101 Course Overview

### ISSUE THREAD

**Issue by cmaliwal** [fetchai/deprecated-docs#845]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Incorrect or missing Content

### Expected Behavior / Content

The course overview for "Agents 101 for AI Engine" should mention the correct version of the AI Engine package, which is 0.5.0.

https://pypi.org/project/uagents-ai-engine/

### Observed Behavior / Content

The course overview currently mentions an outdated version of the AI Engine package, which is 0.4.0.

<img width="825" alt="Screenshot 2024-08-09 at 10 59 21 PM" src="https://github.com/user-attachments/assets/fd6ffe83-e96f-4575-9626-c53b164bada5">

### Additional Information (Optional)

```markdown
Suggestion: Dynamically display the latest version number of the AI Engine package.
```

**Comment by FelixNicolaeBucsa** [comment]
I have already fixed this in a PR

**Comment by FelixNicolaeBucsa** [comment]
https://github.com/fetchai/docs/pull/844
