### ISSUE TITLE
Update Next.js from 13.4.10 to 14.2.5

### ISSUE THREAD

**Issue by cmaliwal** [fetchai/deprecated-docs#851]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) to make sure this feature has not already been requested

### Feature

Currently our docs is using Next.js version 13.4.10. Although there are no known security vulnerabilities in this version, it is outdated. The latest version, 14.2.5, includes new features, performance improvements, and bug fixes.

**Comment by devjsc** [comment]
Scheduled to update 24th of Aug 2024.
