### ISSUE TITLE
We need to update the tags in the courses section on the docs landing page and on the individual course pages.

### ISSUE THREAD

**Issue by cmaliwal** [fetchai/deprecated-docs#856]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) to make sure this feature has not already been requested

### Feature

![image](https://github.com/user-attachments/assets/8cc1d066-389a-4896-8976-87193073b32c)

the "User-flow" tag doesn’t make much sense to me
![image](https://github.com/user-attachments/assets/56c3c261-b5a5-4f11-88d1-c73491aee8d7)
![image](https://github.com/user-attachments/assets/4ead5fff-7d33-4863-95a4-0297bfd89213)

**Comment by FelixNicolaeBucsa** [comment]
Both tags in guides and those below courses where fixed with PR857

**Comment by FelixNicolaeBucsa** [comment]
@devjsc PR for this: https://github.com/fetchai/docs/pull/886
