### ISSUE TITLE
Add Fetch Network Introduction Section under Concepts

### ISSUE THREAD

**Issue by cmaliwal** [fetchai/deprecated-docs#908]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) to make sure this feature has not already been requested

### Feature

We should consider adding an introductory section about the Fetch network under the Concepts category. This section would provide an overview of the Fetch network, explaining its core principles, key components, and how it fits within our broader ecosystem. This will help users better understand the foundation of the technology and how it relates to the other concepts discussed.

![image](https://github.com/user-attachments/assets/22b0aaac-b34e-4d89-8aa6-188ed02e861a)

**Comment by FelixNicolaeBucsa** [comment]
PR: https://github.com/fetchai/docs/pull/911
