### ISSUE TITLE
Re-order Intermediate topics

### ISSUE THREAD

**Issue by tanaygodse** [fetchai/deprecated-docs#913]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) to make sure this feature has not already been requested

### Feature

Title: Re-order Intermediate topics

Suggested Change:
Change the order of "Intermediate Topics".
Move the "Agent Handlers" tutorial above the "Communicating with other agents" tutorial.

Justification: 
We are using on_interval and on_message handlers in the "Communicating with other agents" tutorial, so changing the order will make the progression more intuitive.

**Comment by devjsc** [comment]
Hey @tanaygodse, this one is a little awkward, you're right it makes sense to introduce a topic before we use it, but I really want the developer to build a pair of agents communicating before getting into the details of handlers. 

Will have a think about this 👍

**Comment by devjsc** [comment]
Closing issue as we're happy with ordering in the guides.
