### ISSUE TITLE
Add uAgents API documentation

### ISSUE THREAD

**Issue by mau-fyi** [fetchai/deprecated-docs#930]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) to make sure this feature has not already been requested

### Feature

Under https://fetch.ai/docs/references/ there should be an entry for uAgents. uAgents is comprised of many classes that need API documentation. Context, Agent, Model, etc should have sections that are easy to find describing their purpose and their methods. These documents are partially listed under https://fetch.ai/docs/apis/uAgents/ however, from https://fetch.ai/docs/references/ it is difficult to navigate to https://fetch.ai/docs/apis/uAgents/. Additionally, the uAgents section is not formatted nicely.

_No response_

**Comment by devjsc** [comment]
Hi, this does exist we just don't have it linked in the menu due to not being happy with the implementation. It's high on our list to update, so this will be coming soon. 

See [refs](https://github.com/fetchai/docs/tree/main/pages/references/uagents)
