### ISSUE TITLE
Outdated documentation for AI Engine Chat API

### ISSUE THREAD

**Issue by tanaygodse** [fetchai/deprecated-docs#935]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Incorrect or missing Content

### Expected Behavior / Content

Documentation should capture the latest API Key based approach for getting the Bearer token.

### Observed Behavior / Content

The docs currently ask the user to copy the fauna token from the Agentverse website using Application Tab in the developer mode on the browser. 

However a new method for getting an "API Key" has been added to Agentverse. 

This should be updated in the documentation.

**Comment by cmaliwal** [comment]
<img width="495" alt="Screenshot 2024-09-06 at 9 39 31 AM" src="https://github.com/user-attachments/assets/2adc9630-b403-4494-8692-3f9127e99916">
