### ISSUE TITLE
Agentverse API not working on chrome execute functionality given on Hosting API documentation on Fetch.ai Docs

### ISSUE THREAD

**Issue by sanket6399** [fetchai/deprecated-docs#938]
### Prerequisites

- [X] I checked the [documentation](https://fetch.ai/docs) and found no answer to my problem
- [X] I checked the [existing issues](https://github.com/fetchai/uAgents/issues) and made sure there are no similar bug reports

### Category

Bug (unexpected behavior)

### Expected Behavior

After putting bearer token and other parameters, the request should be sent to agentverse.

### Observed Behavior

I am getting missing credentials even after putting right auth tokens.

### To Reproduce

Go on https://fetch.ai/docs/apis/agentverse/hosting#request-and-response-library
Put all your auth credentials from Agentverse API key and then try to execute

### Version

v

**Comment by gautamgambhir97** [comment]
@sanket6399 it's working fine , can you please test it again 
![image](https://github.com/user-attachments/assets/6a6aec1d-34a0-4282-a498-e29e63b5af9a)

or if there is any specific agentverse API is not working, please let us know

**Comment by devjsc** [comment]
Close as I am unable to reproduce, if you encounter this error again please reopen issue.
