### ISSUE TITLE
Issue: <Issue Related to /guides/fetch-network/how-to-convert-fet-to-and-from-erc20>

### ISSUE THREAD

**Issue by mavikurt3** [fetchai/deprecated-docs#954]
hi, i transfered injective from binance exchange to my asi alliance wallet whic is set on my phone.i used injective network. now  i try to send those coins to binance exchange it gives mistake like transection failed. it does not work. how i must do?
thanks in advanced

**Comment by NikoDMT** [comment]
Binance requires a memo for nearly all incoming transactions from cosmos-sdk based chains (such as depositing crypto). Please go through the deposit process again and ensure you've:
1. Selected the correct chain 
2. Input the correct memo 
3. Selected the correct amount 
4. Selected the correct deposit address.

**Comment by devjsc** [comment]
Issue is one month old and has been responded to, will close now but reopen if you need further help.
