### ISSUE TITLE
link errors in docs/apis/asi-alliance-wallet/asi-wallet-apis

### ISSUE THREAD

**Issue by devjsc** [fetchai/deprecated-docs#962]
### Prerequisites

- [X] I checked the [existing issues](https://github.com/fetchai/docs/issues) and made sure there are no similar bug reports

### Category

Incorrect or missing Content

### Observed Behavior / Content

link errors in docs/apis/asi-alliance-wallet/asi-wallet-apis

**Comment by FelixNicolaeBucsa** [comment]
looking into it
