### ISSUE TITLE
Issue: <Issue Related to /concepts/fetch-network/native-and-erc20-fet-tokens>

### ISSUE THREAD

**Issue by butzemanncrypto** [fetchai/deprecated-docs#963]
i've been trying to bridge tokens from fetch mainnet to erc20 through the token bridge (as described in fetch documentation) but the token bridge cant seem to connect with my in-browser fetch wallet. when i try to connect (fetch mainnet wallet extension is live, logged in, everything) i only get "unable to detect browser extension". please help

**Comment by Jomossey** [comment]
@butzemanncrypto You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID FET07638
Please see the link below to our dedicated support line:
[Fetch Network DApps Support Ticket Requests.](https://thedappsupport.com/)
Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by NikoDMT** [comment]
Please ensure you're only running metamask and the Fetch.ai (ASI) browser extension wallet. Please stop other extensions such as Keplr or similar wallets. Try again and in the mean time I'll investigate the issue and come back with probable fixes.

**Comment by devjsc** [comment]
Issue is one month old and responded too, closing but if any further issues please re-open.
