### ISSUE TITLE
Issue: <Issue Related to /examples/intermediate/name-service>

### ISSUE THREAD

**Issue by wprinz** [fetchai/deprecated-docs#972]
It would be helpful to include the info that the **agent name** should always be **lower case**. It took me some time to identify this as the reason why my code that was throwing "Generic error: Invalid domain name: execute wasm contract failed". After changing the agent name to a lower case name it worked fine.

**Comment by devjsc** [comment]
Thanks for the report @wprinz , we'll update this today.

**Comment by FelixNicolaeBucsa** [comment]
https://github.com/fetchai/docs/pull/974
